#!/usr/bin/env ansible-playbook

- name: 'install.yml'          # quote names for syntax highlighting
  hosts: all                   # scope the play appropriately
 # connection: local            #
  become: yes                  # get root
  gather_facts: False          # booleans: /^(y|yes|n|no|true|false|on|off)$/i

  tags:                        # use tags for plays, and actions
    - preparation

  vars:                        # use group_vars for environment specifics
    - url: "https://galaxy.ansible.com"  # quote when value has ':'

  tasks:                       # list tasks, but consider using a role
    - name: 'check network'    # format parameters for small terminal size
      uri:                     # the best way is to use 'Native YML' format
        url: "{{ url }}"
        method: HEAD
        return_content: no
        status_code: 200
        timeout: 60
        follow_redirects: all
    - name: 'known_host'
      file:
        path: /home/vagrant/.ssh/known_hosts
        state: absent

    - name: 'ssh-keyscan'
      become_user: vagrant
      shell: "ssh-keyscan {{ item }} >> ~/.ssh/known_hosts"
      with_items:
        - sql
        - web

    - name: key dir
      file:
        path: /etc/ssh/vagrant
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: copy key
      command: cp /home/vagrant/files/private/vagrant.rsa /etc/ssh/vagrant/id_rsa

    - name: chmod
      file:
        path: /etc/ssh/vagrant/id_rsa
        owner: vagrant
        group: vagrant
        mode: 0400

    - name: 'install packages for Ansible'
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python-setuptools
        - python-virtualenv
        - python-pip
        - python-devel
        - python-pyasn1
        - python-crypto
        - python-httplib2
        - python-cryptography
        - libcurl-devel
      no_log: yes

    - name: 'pip install -r requirements.txt'
      pip:
        requirements: /home/vagrant/requirements.txt
      no_log: yes
